# Generated by Django 5.2.8 on 2025-11-16 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Password Reset', 'password_reset'), ('Network Down', 'network_down'), ('Software Install', 'software_install'), ('Hardware Failure', 'hardware_failure'), ('Email Issue', 'email_issue'), ('Printer Issue', 'printer_issue'), ('Security Incident', 'security_incident'), ('Application Bug', 'application_bug'), ('Server Down', 'server_down'), ('Other', 'other')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'issue_type',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('Lead', 'lead'), ('Associate', 'associate')], max_length=20)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('submitter_fullname', models.CharField(max_length=255)),
                ('submitter_email', models.EmailField(max_length=254)),
                ('submitter_department', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('attachment', models.CharField(blank=True, help_text='Path to the file in object storage', max_length=500, null=True)),
                ('status', models.CharField(choices=[('New', 'new'), ('Assigned', 'assigned'), ('In Progress', 'in_progress'), ('Resolved', 'resolved'), ('Closed', 'closed')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_logger.issuetype')),
            ],
            options={
                'db_table': 'issue',
            },
        ),
        migrations.CreateModel(
            name='IssueHistoryTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='ticket_logger.issue')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket_logger.staff')),
            ],
            options={
                'db_table': 'issue_history_track',
            },
        ),
        migrations.CreateModel(
            name='IssueAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text='Optional notes about the assignment', null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ticket_logger.issue')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Staff who performed the assignment (lead)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by_me', to='ticket_logger.staff')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issues', to='ticket_logger.staff')),
            ],
            options={
                'db_table': 'issue_assignment',
            },
        ),
    ]
